version: '3.3'

volumes:
    simples-mysql-data:
        driver: local

services:
    nginx:
        container_name: simples-nginx
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - .:/app
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        container_name: simples-php
        image: mehrdadkhah/php7
        volumes:
            - .:/app
    mysql:
        container_name: simples-mysql
        volumes:
            - simples-mysql-data:/var/lib/mysql
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: simples
    phpmyadmin:
        container_name: simples-pma
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_ARBITRARY: 1
        links:
            - mysql